flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- poly-graph
- poly-graph-persistent
setup-info:
  ghc:
    linux64:
      8.0.0.20160421:
        url: https://downloads.haskell.org/~ghc/8.0.1-rc4/ghc-8.0.0.20160421-x86_64-deb8-linux.tar.xz
        sha1: 6e8bd7c96fa46da0b8c12bf9d62f006940adfe67
extra-deps:
- HUnit-1.3.1.1
- QuickCheck-2.8.2
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-0.11.2.0
- aeson-compat-0.3.3.0
- ansi-terminal-0.6.2.3
- async-2.1.0
- attoparsec-0.13.0.2
- auto-update-0.1.3.1
- base-compat-0.9.1
- base-orphans-0.5.4
- base64-bytestring-1.0.0.1
- bifunctors-5.3
- blaze-builder-0.4.0.2
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- bytestring-builder-0.10.6.0.0
- comonad-5
- conduit-1.2.6.4
- conduit-extra-1.1.13.1
- contravariant-1.4
- distributive-0.5.0.2
- dlist-0.7.1.2
- easy-file-0.2.1
- exceptions-0.8.2.1
- fail-4.9.0.0
- fast-logger-2.4.6
- free-4.12.4
- generics-eot-0.2.1
- hashable-1.2.4.0
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- http-api-data-0.2.2
- kan-extensions-5.0.1
- lens-4.14
- lifted-base-0.2.3.6
- markdown-unlit-0.4.0
- mmorph-1.0.6
- monad-control-1.0.1.0
- monad-logger-0.3.18
- monad-loops-0.4.3
- mtl-2.2.1
- nats-1.1
- network-2.6.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.1.0
- path-pieces-0.2.1
- persistent-2.5
- persistent-sqlite-2.5
- persistent-template-2.5.1
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- quickcheck-io-0.1.2
- random-1.1
- reflection-2.1.2
- resource-pool-0.2.3.2
- resourcet-1.1.7.3
- scientific-0.3.4.6
- semigroupoids-5.0.1
- semigroups-0.18.1
- setenv-0.1.1.3
- silently-1.2.5
- stm-2.4.4.1
- stm-chans-3.0.0.4
- streaming-commons-0.1.15.4
- syb-0.6
- tagged-0.8.4
- text-1.2.2.1
- tf-random-0.5
- time-locale-compat-0.1.1.1
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-time-0.3.6
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- void-0.7.1
- zlib-0.6.1.1
compiler: ghc-8.0.0.20160421
resolver: ghc-8.0.0.20160421
